### ISSUE TITLE
Magic 8 ball type of function

### ISSUE THREAD

**Issue by MJholland** [quoter/quoter#412]
**Is your feature request related to a problem? Please describe.**
Before using quoter we used MEE6 with a custom command to do quotes (it's really bad at rng quote pulling lol). One fun thing with this was that users would be able to write things like "!quote about the server" or "!quote about my server lore" and their command message was shown with the quote being shown after. It was sort of like a magic 8 ball type thing but the answers were saved quotes. While the results didn't always work, people enjoyed the random nature of it and when it did work it made it more funny. 

**Describe the solution you'd like**
And option of some kind to add additional text after the /quote command so users can add their own context to the random quote given. 

**Describe alternatives you've considered**
probably just keep the MEE6 implementation for people that still want to do the thing 

**Additional context**
Here's a screenshot of what our old basic version looks like. What really made it fun was when the returned quote randomly fit the context, people would start to claim to be a bot whisperer and stuff, its pretty entertaining.
<img width="679" alt="Screenshot 2024-02-26 at 12 21 07 PM" src="https://github.com/quoter/quoter/assets/16650658/c7d7d553-7d62-4148-9b51-46be4e01ede0">

**Comment by n1ckoates** [comment]
This is a great idea. The main issue I see is that slash command arguments are not shown unless you click on the command name. There's two ways to workaround this:

1. Add a regular message based command to do this, like shown in your example. This would probably be the best *looking* solution, but there's significant technical challenges. Quoter cannot currently read message content, so it would have to apply for this intent with Discord - and probably be rejected because this can be done with slash commands. Additionally, current servers would have to re-invite the bot to get this permission. Finally, this would increase memory/CPU usage because Quoter would then be receiving *every* message sent in all servers.
2. Add a `/8-ball` slash command. This would look worse, because the 8-ball "context" wouldn't be sent by the user. Instead, the 8-ball context would be repeated back by Quoter in the response. I don't think that's a big deal, and is a better option given the downsides of the alternative.

Would be great to hear your feedback on this. Thanks for the suggestion!

**Comment by n1ckoates** [comment]
This will be in the next release of Quoter.

**Comment by MJholland** [comment]
Yay! Thanks so much, the server will love it
